#!/usr/bin/env ruby

$LOAD_PATH.unshift("#{__dir__}/../lib")

require "optparse"
require "grepfruit"

options = {
  path: Dir.pwd,
  regex: /TODO/,
  exclude: [["log"], ["tmp"], ["vendor"], ["node_modules"], ["assets"]],
  search_hidden: false
}

OptionParser.new do |opts|
  opts.banner = "Usage: grepfruit [options] PATH"

  opts.on("-r", "--regex REGEX", Regexp, "Regex pattern to search for") do |regex|
    options[:regex] = regex
  end

  opts.on("-e", "--exclude x,y,z", Array, "Comma-separated list of files and directories to exclude") do |exclude|
    options[:exclude] = exclude.map! { |path| path.split("/") }
  end

  opts.on("-s", "--search-hidden", TrueClass, "Search hidden files and directories") do |search_hidden|
    options[:search_hidden] = search_hidden
  end
end.parse!

options[:path] = ARGV[0] if ARGV[0]

Grepfruit.run(**options)
